### ISSUE TITLE
nbind.js throws error

### ISSUE THREAD

**Issue by mphealy** [vadimdemedes/yoga-layout-prebuilt#2]
yoga-layout-prebuilt is being used by @reactpdf/renderer (react-pdf.org). 
In some situations nbind.js throws a 'not defined' error on line 1146: 
`_a = _typeModule(_typeModule), `

simply changing this segment in my node_modules to

`var _a = _typeModule(_typeModule); `

resolves the issue. 

Not 100% sure how to request this to be resolved. I'm not sure how to dig into the process that is building this, and guessing you don't want a pull request on changes to nbind.js since that looks to be the result...

**Comment by vadimdemedes** [comment]
Yeah, this issue should be reported on `yoga-layout` repo, as this module just contains the build of it. You can do that here: https://github.com/facebook/yoga.

**Comment by privatenumber** [comment]
It happens when `nbind.js` is bundled and the bundler converts the module to strict mode (which pretty much all bundlers do).

You can get around this by converting `yoga-layout-prebuilt` to an external dependency so it's left untouched.

Alternatively, if you can write a plugin for your bundler, you can add this at the top of the `nbind.js` file to patch it so it can be bundled:
```js
'use strict';
var _a;
```

-----

I'm not too familiar with node-gyp, but I wonder if this code is a result of node-gyp building. Curious if using the latest version to build would fix it.

**Comment by gfox1984** [comment]
See https://github.com/facebook/yoga/issues/1048#issuecomment-1286895380 for a patch.

**Comment by airtonix** [comment]
Broken in deno too
